-- Generated by semantics_builder on 2026-07-04T16:54:24.719661Z
-- Source schemas: ANALYTICS  | tables: DIM_CUSTOMERS, FCT_SAAS_BILLING
-- Model: minimax/minimax-m3

{{ config(materialized='semantic_view') }}

TABLES (
  customers AS {{ source('raw', 'DIM_CUSTOMERS') }} PRIMARY KEY (CUSTOMER_ID) COMMENT = 'The table contains records of customer information. Each record represents a single customer and includes details about their company and contact information.',
  billing AS {{ source('raw', 'FCT_SAAS_BILLING') }} PRIMARY KEY (BILLING_ID) COMMENT = 'The table contains records of subscription billing information. Each record represents a customer''s subscription plan and includes details about their plan type, billing status, and financial metrics.'
)

RELATIONSHIPS (
  customer_billing AS billing(CUSTOMER_ID) REFERENCES customers
)

DIMENSIONS (
  customers.COMPANY_NAME AS COMPANY_NAME COMMENT = 'The name of the company.',
  customers.CUSTOMER_ID AS CUSTOMER_ID COMMENT = 'Unique identifier for the customer.',
  customers.INDUSTRY AS INDUSTRY COMMENT = 'The industry in which the customer operates.',
  billing.BILLING_DATE AS BILLING_DATE COMMENT = 'Date of the billing.',
  billing.BILLING_ID AS BILLING_ID COMMENT = 'Unique identifier for the billing record.',
  billing.CUSTOMER_ID AS CUSTOMER_ID COMMENT = 'Unique identifier for the customer.',
  billing.IS_ACTIVE AS IS_ACTIVE COMMENT = 'Indicates whether the billing record is active.',
  billing.PLAN_TYPE AS PLAN_TYPE COMMENT = 'The type of plan subscribed by the customer.'
)

METRICS (
  billing.total_mrr AS SUM(MRR_AMOUNT) COMMENT = 'Total Monthly Recurring Revenue',
  billing.net_mrr AS SUM(MRR_AMOUNT) - SUM(DISCOUNT_AMOUNT) COMMENT = 'MRR minus any applied discounts',
  billing.churned_revenue AS SUM(IFF(IS_ACTIVE = FALSE, MRR_AMOUNT, 0)) COMMENT = 'Revenue lost from canceled plans'
)

COMMENT = 'Semantic view combining customer information with subscription billing records, covering company, industry, plan, billing date, and active status, with certified MRR, net MRR, and churned revenue metrics.'
